# `dplyr`

## `case_when()`

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">💡 dplyr::case_when goes really well with geom_text (or ggrepel) for when you want to programmatically label a few of the most interesting features in your <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> plots! And the criteria can be as complex as you want 🎉 <a href="https://t.co/0jUp1uarde">pic.twitter.com/0jUp1uarde</a></p>&mdash; James Goldie (@rensa_co) <a href="https://twitter.com/rensa_co/status/976340414016843776?ref_src=twsrc%5Etfw">March 21, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 

## `mutate_at()`

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">dplyr trick: mutate_at() takes a range of consecutive columns, with var(col1:coln) if you want to batch convert a bunch of columns: <a href="https://t.co/RrvMQ9ols1">pic.twitter.com/RrvMQ9ols1</a></p>&mdash; Vince Buffalo (@vsbuffalo) <a href="https://twitter.com/vsbuffalo/status/831651327411302404?ref_src=twsrc%5Etfw">February 14, 2017</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 

## `mutate_if()`

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Great dplyr tip! <br><br>df %&gt;% mutate_if(is.factor, as.character)<br><br>Converts all factor columns to characters. <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/tidyverse?src=hash&amp;ref_src=twsrc%5Etfw">#tidyverse</a></p>&mdash; Geoffrey Thomson (@GojThomson) <a href="https://twitter.com/GojThomson/status/847241896015441921?ref_src=twsrc%5Etfw">March 30, 2017</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 

## `summarise_at()`

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Todays fun <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/tidyverse?src=hash&amp;ref_src=twsrc%5Etfw">#tidyverse</a> function! dplyr::summarize_at()<br>Applies multiple summary functions to multiple variables!<br><br>mtcars %&gt;% <br> group_by(cyl, am) %&gt;% <br> summarize_at(vars(disp, hp, mpg), funs(mean, sd)) <a href="https://t.co/JGN6Guebd6">pic.twitter.com/JGN6Guebd6</a></p>&mdash; Thomas Mock (@thomas_mock) <a href="https://twitter.com/thomas_mock/status/967467213623119873?ref_src=twsrc%5Etfw">February 24, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
